# Generated by Django 4.1 on 2023-11-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termino',
            name='titulo',
            field=models.CharField(default='Default Value', max_length=100),
            preserve_default=False,
        ),
    ]
