# Generated by Django 4.1 on 2023-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosario', '0004_alter_palabra_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
